[window]
# Fenstergröße in Zeichen
dimensions = { columns = 147, lines = 44 }

# Abstand vom Rand in Pixeln
padding = { x = 8, y = 8 }

# Transparenz (0.0 = transparent, 1.0 = opak)
opacity = 0.90

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"
