---
- name: Install tools via shell on ubuntu
  hosts: localhost
  tasks: 
    - name: Add Rust to PATH for Fish
      shell: source {{ ansible_env.HOME }}/.cargo/env.fish
      args:
        executable: /usr/bin/fish

    - name: Create directory for github projects
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/code/github"
        state: directory
        recurse: yes
        mode: '0755'

    - name: Clone eza repository
      git:
        repo: https://github.com/eza-community/eza.git
        dest: "{{ ansible_env.HOME }}/code/github/eza"
        force: yes
      
    - name: Install eza using cargo
      shell: cargo install --path .
      args:
        chdir: "{{ ansible_env.HOME }}/code/github/eza"
        executable: /usr/bin/fish
  
    - name: Install Fisher plugin manager for Fish
      shell: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
      args:
        executable: /usr/bin/fish

    - name: Install theme for fish
      shell: fisher install axkirillov/tokyonight-fish
      args:
        executable: /usr/bin/fish

    - name: Install fishline
      shell: fisher install 0rax/fishline
      args:
        executable: /usr/bin/fish

    - name: Install tmux package manager
      git: 
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
